### ISSUE TITLE
The current method to get the magical data does not work : (

### ISSUE THREAD

**Issue by MacbethRene** [jalizadeh/Download-Instagram-Live-Video#1]
I cant find the json string from the plugin in the same way that you described.
Which value is the one you actually need? thanks!

**Comment by jalizadeh** [comment]
Dear @MacbethRene, follow the step #5 carefully and select the fields, exactly like the numbers in the photo. In number 3, you should select "key: cachedPositiveLiveStories", then copy all the data in column "value"
